(function() {
    if (typeof GameData === 'undefined' || !GameData) return;
    if (!GameData.skillConfig || typeof GameData.skillConfig !== 'object') GameData.skillConfig = {};
    GameData.skillConfig['阴阳道'] = [
        {
            id: 'y_1',
            name: '五仙',
            realm: '寻道',
            type: 'active',
            mpCost: 35,
            baseDmg: 25,
            heal: 0,
            text: '阴阳消长，五行转移！',
            chant: '“阴阳消长，五行转移！”',
            cost: { mp: 35 },
            omenDelta: 0,
            chaosDelta: 0,
            tags: ['spell', 'yang'],
            sourceDao: '阴阳道',
            category: 'core'
        },
        {
            id: 'y_2',
            name: '五鬼',
            realm: '寻道',
            type: 'active',
            mpCost: 35,
            baseDmg: 25,
            heal: 0,
            text: '阴阳翻覆，阴影应召！',
            chant: '“阴阳翻覆，阴影应召！”',
            cost: { mp: 35 },
            omenDelta: 0,
            chaosDelta: 0,
            tags: ['spell', 'yin'],
            sourceDao: '阴阳道',
            category: 'core'
        },
        {
            id: 'y_3',
            name: '神压',
            realm: '寻道',
            type: 'active',
            mpCost: 60,
            baseDmg: 60,
            heal: 0,
            text: '如迁神怒，骨碎成灰！',
            chant: '“如迁神怒，骨碎成灰！”',
            cost: { mp: 60 },
            omenDelta: 0,
            chaosDelta: 0,
            tags: ['spell', 'aoe', 'stun'],
            sourceDao: '阴阳道',
            category: 'core'
        },
        {
            id: 'y_4',
            name: '逆转',
            realm: '寻道',
            type: 'active',
            mpCost: 80,
            baseDmg: 0,
            heal: 0,
            text: '阴阳易位，乾坤倒置。',
            chant: '“阴阳易位，乾坤倒置。”',
            cost: { mp: 80 },
            omenDelta: 2,
            chaosDelta: 0,
            tags: ['env', 'invert'],
            sourceDao: '阴阳道',
            category: 'core'
        },
        {
            id: 'y_5',
            name: '替身纸人',
            realm: '寻道',
            type: 'passive',
            mpCost: 0,
            baseDmg: 0,
            heal: 0,
            text: '一纸替身，代你受劫。',
            chant: '“一纸替身，代你受劫。”',
            cost: { },
            omenDelta: 0,
            chaosDelta: 0,
            tags: ['passive', 'death_save'],
            sourceDao: '阴阳道',
            category: 'core'
        }
    ];
})();
